### PR TITLE
Prototype Minikube deployment

### LINKED ISSUE #6: AILL: Prototype Minikube deployment
As a site administrator I want to deploy the IOP and Kubernetes is the enterprise grade containerisation technology.

As a developer I don't want to have ave a full fledged Kubernetes cluster running on my laptop, but I can use Minikube to mimic that.

This task packages the Reva docker container and the other necessary software components into HELM chart that can be deployed using Minikube.

### PR DESCRIPTION
**Pull request by mateusz-garlacz**
Closes #6

### CODE REVIEW

**Comment by mateusz-garlacz** [comment]
@labkode I think it is ready to merge

**Comment by labkode** [comment]
Tested and it works. 

Following the documentation there are two points to improve:

1) Mention to install helm
2) Clarify that you only need to run `eval $(minikube docker-env)` if you use the docker driver.

**Comment by ebocchi** [comment]
Sorry for commenting on a close one:
- Can we make a script to automate the installation of minikube and helm? I should have something pre-cooked and I am happy to share.
- We should consider to have the config passed as ConfigMap rather that making the config file part of the image.

I am happy to take this offline if preferred

**Comment by labkode** [comment]
@ebocchi can you make your comments a new issue? easier to track

**Comment by ebocchi** [comment]
Sure. Done here: https://github.com/sciencemesh/sciencemesh/issues/38

**Pull request merged**
