### PR TITLE
Configuration guideline added for json and dummy data drivers.

### PR DESCRIPTION
**Pull request by redblom**
Configuration guideline added for json and dummy data drivers.

- Read metrics from external scripts #125

### CODE REVIEW

**Review by michielbdejong — APPROVED** [review]
LGTM

Is this still the latest up to date information @redblom ?

**Comment by redblom** [comment]
> LGTM
> 
> Is this still the latest up to date information @redblom ?

Yes, also just tested it on the current reva version.

**Comment by redblom** [comment]
Rebased again.

**Comment by Daniel-WWU-IT** [comment]
@redblom Is there still (after, uh, like 1.5 years) anything that blocks this from being merged? Since people should expose their figures through this driver and this would be good documentation on that, I'd happily merge this PR unless you disagree.

**Comment by redblom** [comment]
> @redblom Is there still (after, uh, like 1.5 years) anything that blocks this from being merged? Since people should expose their figures through this driver and this would be good documentation on that, I'd happily merge this PR unless you disagree.

I'm all for merging :) and as I wrote the guideline is still valid.
Thank you.

**Pull request merged**
