### PR TITLE
Use the upstream docker images for REVA and Phoenix and update the docs accordingly

### LINKED ISSUE #20: AILL: use upstream Docker repositories
Don't build phoenix and reva to create own images. Rely on the upstream ones:

https://hub.docker.com/r/cs3org/revad

https://hub.docker.com/r/owncloud/phoenix/

### PR DESCRIPTION
**Pull request by SamuAlfageme**
This replaces the need to build the containers in order to install the reva-phoenix helm chart for the minikube example. It replaces them with the upstream: 

- [cs3org/revad](https://hub.docker.com/r/cs3org/revad)
- [owncloud/phoenix](https://hub.docker.com/r/owncloud/phoenix)

I'm marking this PR as draft for the time being since there's still one detail to figure out for this to work. Since [owncloud/phoenix](https://hub.docker.com/r/owncloud/phoenix) is built `FROM` [webhippie/nginx](https://hub.docker.com/r/webhippie/nginx); it exposes port 8080 instead of the usual Phoenix' 8300. This required an adjustment on Phoenix k8s service object and:

- [x] ~Will require [`http.services.oidcprovider.clients.phoenix.redirect_uris`](https://github.com/cs3org/reva/blob/dfa88617150249f1ece6c0b05f819518c8c63f82/examples/oc-phoenix/frontend.toml#L45) to be switched from `8300` to `8080` for localhost URLs.~

cc/ @labkode is there an easy way (e.g. a config patch) to override **individual values** of revad's config rather than replacing the value on `frontend.toml`? 

This would fix #20 #18 #19 and collaterally #38

### CODE REVIEW

**Comment by SamuAlfageme** [comment]
cc/ @mateusz-garlacz

**Comment by labkode** [comment]
Hi @mateusz-garlacz, @SamuAlfageme will contribute to the K8s area, if you are already doing some job please start always with a pull request, that is the only way to keep track of ongoing work. Please coordinate with @SamuAlfageme if there is some parts that you have added to be included in this PR.

**Comment by labkode** [comment]
> cc/ @labkode is there an easy way (e.g. a config patch) to override **individual values** of revad's config rather than replacing the value on `frontend.toml`?
> 

No, the current way is to change the configuration file.

**Comment by SamuAlfageme** [comment]
@mateusz-garlacz I like the way you solved the issue with the Phoenix (https://github.com/sciencemesh/sciencemesh/pull/42#issue-399707414) ports on [your branch](https://github.com/mateusz-garlacz/sciencemesh/blob/dae76b21227bea9e31602e349ec77556cf6479f2/k8s/reva-phoenix/templates/service/phoenix-svc.yaml#L7-L9) - i.e. using a `targetPort`. Feel free to push it to this branch.

**Comment by ebocchi** [comment]
Looks good to me as well

**Pull request merged**
